name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      # - daniel/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      # Set up the Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Google Container Registry
      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Set GCP Project ID as environment variable
      - name: Set env variables
        run: echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      # --- Backend Deployment ---
      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/fastapi-backend:latest
          platforms: linux/amd64

      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        run: |
          gcloud run deploy fastapi-backend \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/fastapi-backend:latest \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated \
            --max-instances=1 \
            --set-env-vars SPOONACULAR_API_KEY=${{ secrets.SPOONACULAR_API_KEY }}

      - name: Retrieve Backend Service URL
        id: get_backend_url
        run: |
          SERVICE_URL=$(gcloud run services describe fastapi-backend --region us-east4 --platform managed --format='value(status.url)')
          echo "Backend Service URL: ${SERVICE_URL}"
          echo "service_url=${SERVICE_URL}" >> $GITHUB_OUTPUT

      # --- Frontend Deployment ---
      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/vite-frontend:latest
          platforms: linux/amd64
          build-args: |
            VITE_BACKEND_URL=${{ steps.get_backend_url.outputs.service_url }}

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy vite-frontend \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/vite-frontend:latest \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated \
            --max-instances=1
