name: E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean install dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install
          npm install @rollup/rollup-linux-x64-gnu

      - name: Build the project
        run: cd frontend && npm run build

      - name: Start preview server
        run: cd frontend && npm run preview &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4173

      - name: Run Cypress tests
        run: cd frontend && npm run cy:run
