name: Run Pytest on Backend

on:
  pull_request:
    branches:
      - main

jobs:
  # Backend tests with pytest (FastAPI)
  test-backend:
    runs-on: ubuntu-latest

    env:
      SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest  # Add this line explicitly

      # Step 4: Debug Environment
      - name: Debug Environment
        run: |
          cd backend
          source venv/bin/activate
          echo "API Key presence check (should show as '***'):"
          echo "$SPOONACULAR_API_KEY"
          echo "Python environment:"
          which python
          python --version

      # Step 5: Run pytest for backend
      - name: Run pytest tests
        run: |
          cd backend
          source venv/bin/activate
          python -m pytest -v  # Added -v for verbose output
